"""message_sender_type_name

Revision ID: a9d66a9a1bb4
Revises: 94a343454d06
Create Date: 2025-12-16 12:06:46.525569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9d66a9a1bb4'
down_revision: Union[str, Sequence[str], None] = '94a343454d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('text', sa.Text(), nullable=False), schema='db_schema')
    op.drop_constraint(op.f('messages_sender_type_id_fkey'), 'messages', schema='db_schema', type_='foreignkey')
    op.create_unique_constraint(
        'uq_sender_types_name',  # имя ограничения
        'sender_types',
        ['name'],
        schema='db_schema'
    )
    op.alter_column('messages', 'sender_type_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False,
               schema='db_schema')
    op.create_foreign_key(None, 'messages', 'sender_types', ['sender_type_id'], ['name'], source_schema='db_schema', referent_schema='db_schema')
    op.drop_column('messages', 'token_id', schema='db_schema')
    op.drop_column('messages', 'message_text', schema='db_schema')
    op.drop_column('messages', 'timestamp', schema='db_schema')
    op.drop_column('sender_types', 'created_at', schema='db_schema')
    op.drop_column('sender_types', 'id', schema='db_schema')
    op.drop_column('sender_types', 'updated_at', schema='db_schema')

    op.bulk_insert(
        sa.table('sender_types',
                 sa.column('name', sa.String),
                 schema='db_schema'
                 ),
        [
            {
                'name': 'user',
            },
            {
                'name': 'chat',
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sender_types', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False), schema='db_schema')
    op.add_column('sender_types', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False), schema='db_schema')
    op.add_column('sender_types', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False), schema='db_schema')
    op.add_column('messages', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='db_schema')
    op.add_column('messages', sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=False), schema='db_schema')
    op.add_column('messages', sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='db_schema')
    op.drop_constraint(None, 'messages', schema='db_schema', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_type_id_fkey'), 'messages', 'sender_types', ['sender_type_id'], ['id'], source_schema='db_schema', referent_schema='db_schema')
    op.alter_column('messages', 'sender_type_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               schema='db_schema')
    op.drop_column('messages', 'text', schema='db_schema')
    # ### end Alembic commands ###
