"""marmiladki

Revision ID: 94a343454d06
Revises: 30e23480adc0
Create Date: 2025-11-10 10:48:12.810043

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94a343454d06"
down_revision: str | Sequence[str] | None = "30e23480adc0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cards", sa.Column("title", sa.String(length=255), nullable=True), schema="db_schema"
    )
    op.add_column("cards", sa.Column("description", sa.Text(), nullable=True), schema="db_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "description", schema="db_schema")
    op.drop_column("cards", "title", schema="db_schema")
    # ### end Alembic commands ###
