"""marmeladki

Revision ID: 0a21764ca0d4
Revises: 30e23480adc0
Create Date: 2025-11-10 10:46:55.726767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a21764ca0d4'
down_revision: Union[str, Sequence[str], None] = '30e23480adc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('title', sa.String(length=255), nullable=True), schema='db_schema')
    op.add_column('cards', sa.Column('description', sa.Text(), nullable=True), schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'description', schema='db_schema')
    op.drop_column('cards', 'title', schema='db_schema')
    # ### end Alembic commands ###
