"""message_sender_type

Revision ID: 044edf93fdb9
Revises: 94a343454d06
Create Date: 2025-12-15 01:24:02.558975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '044edf93fdb9'
down_revision: Union[str, Sequence[str], None] = '94a343454d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'timestamp', schema='db_schema')
    op.drop_column('messages', 'token_id', schema='db_schema')
    op.alter_column('messages','message_text', new_column_name='text',schema='db_schema')
    # ### end Alembic commands ###
    op.bulk_insert(
        sa.table('sender_types',
                 sa.column('id', postgresql.UUID(as_uuid=True)),
                 sa.column('name', sa.String),
                 sa.column('created_at', sa.DateTime),
                 sa.column('updated_at', sa.DateTime),
                 schema='db_schema'
                 ),
        [
            {
                'id': 'c2a9e7f1-5b83-4d2c-91a6-8f3b0c4d5e6f',
                'name': 'user',
                'created_at': "2024-12-15 12:30:45.123456+00:00",
                'updated_at': "2024-12-15 12:30:45.123456+00:00"
            },
            {
                'id': '9d8a2b7c-4e1f-4a3d-85c9-0b6a1e3f8d2c',
                'name': 'chat',
                'created_at': "2024-12-15 12:30:45.123456+00:00",
                'updated_at': "2024-12-15 12:30:45.123456+00:00"
            }
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='db_schema')
    op.add_column('messages', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='db_schema')
    op.alter_column('messages','text', new_column_name='message_text',schema='db_schema')
    # ### end Alembic commands ###
